DATA_STORE = "data_store/"
ARMY_PATH = DATA_STORE + "army.json"
WARSCROLL_PATH = DATA_STORE + "warscroll.json"
TEST_ARMY_PATH = DATA_STORE + "test_army.json"
TEST_WARSCROLL_PATH = DATA_STORE + "test_warscroll.json"
