sonar.projectKey=edwa5158_simpler-army-builder
sonar.organization=edwa5158
sonar.projectName=simpler-army-builder
sonar.sources=.
sonar.exclusions=**/tests_*.py,**/test_*.py

sonar.tests=.
sonar.test.inclusions=**/tests_*.py,**/test_*.py

sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
